blank_issues_enabled: false
contact_links:
  - name: Visual Studio Issues & Feedback
    url: https://developercommunity.visualstudio.com/
    about: For Visual Studio-related questions, bugs, or feature requests, please use the Visual Studio Developer Community.
