name: Close stale issues

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 0
          days-before-close: 0
          stale-issue-message: ""
          close-issue-message: >
            The scope of this repository has changed.
            For Visual Studio-related questions, please visit the
            [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home).
            If your issue is still relevant to this repository, please feel free to open a new one.
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 1000
